# netlify.toml
[build]
  publish = "public"
  command = "npm install"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self' https://identity.netlify.com; script-src 'self' https://cdn.jsdelivr.net"